name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'staging'
        type: string
  push:
    branches:
      - main
      - staging
  pull_request:
    types:
      - closed
    branches:
      - main
      - staging

env:
  CI: false

jobs:
  build_and_deploy:
    environment:
      name: ${{ github.event.inputs.branch || github.ref_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, staging]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn install

      - name: Load environment variables for main
        if: matrix.branch == 'main'
        run: echo "Loaded environment variables for main"
        env:
          NEXT_PUBLIC_FIREBASE_ADMIN_PROJECTID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_MAIN_PROJECTID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENTEMAIL: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_MAIN_CLIENTEMAIL }}
          NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATEKEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_MAIN_PRIVATEKEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_MISSION_GO_JAPAN_MAIN }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID_MISSION_GO_JAPAN_MAIN }}

      - name: Load environment variables for staging
        if: matrix.branch == 'staging'
        run: echo "Loaded environment variables for staging"
        env:
          NEXT_PUBLIC_FIREBASE_ADMIN_PROJECTID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_STAGING_PROJECTID }}
          NEXT_PUBLIC_FIREBASE_ADMIN_CLIENTEMAIL: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_STAGING_CLIENTEMAIL }}
          NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATEKEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_STAGING_PRIVATEKEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_MISSION_GO_JAPAN_STAGING }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID_MISSION_GO_JAPAN_STAGING }}

      - name: Print environment variables for main
        if: matrix.branch == 'main'
        run: |
          echo "NEXT_PUBLIC_FIREBASE_ADMIN_PROJECTID=$NEXT_PUBLIC_FIREBASE_ADMIN_PROJECTID"
          echo "NEXT_PUBLIC_FIREBASE_ADMIN_CLIENTEMAIL=$NEXT_PUBLIC_FIREBASE_ADMIN_CLIENTEMAIL"
          echo "NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATEKEY=$NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATEKEY"
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY"
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
          echo "NEXT_PUBLIC_FIREBASE_DATABASE_URL=$NEXT_PUBLIC_FIREBASE_DATABASE_URL"
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID"
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"

      - name: Print environment variables for staging
        if: matrix.branch == 'staging'
        run: |
          echo "NEXT_PUBLIC_FIREBASE_ADMIN_PROJECTID=$NEXT_PUBLIC_FIREBASE_ADMIN_PROJECTID"
          echo "NEXT_PUBLIC_FIREBASE_ADMIN_CLIENTEMAIL=$NEXT_PUBLIC_FIREBASE_ADMIN_CLIENTEMAIL"
          echo "NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATEKEY=$NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATEKEY"
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY"
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
          echo "NEXT_PUBLIC_FIREBASE_DATABASE_URL=$NEXT_PUBLIC_FIREBASE_DATABASE_URL"
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID"
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase Hosting for main
        if: matrix.branch == 'main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_MAIN }}
          channelId: live
          projectId: mission-go-japan-app

      - name: Deploy to Firebase Hosting for staging
        if: matrix.branch == 'staging'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MISSION_GO_JAPAN_STAGING }}
          channelId: live
          projectId: mission-go-japan
